### ISSUE TITLE
Nav: Agents fall to death when there is a surface on top of another

### ISSUE THREAD

**Issue by kobechenyang** [reeseschultz/ReeseUnityDemos#30] opened 2020-06-22 03:49 UTC
Hi Reese 

I found a case when I have one surface on top of another one,
![image](https://user-images.githubusercontent.com/8561346/85246760-768a5b80-b400-11ea-909f-2a925a15ec4a.png)
As you can see in my screenshot.  The agents will go to the edge and fall off the surface. Is there something I can do to avoid this? 

Thanks.

**Comment by reeseschultz** [comment] 2020-06-22 15:42
The screenshot is really not enough to tell me what's going on here, so I'm at a disadvantage since I don't have the details you do. One possible problem is this: the bottom surface has holes in it, because each obstacle carves out the nav mesh. Agents can potentially fall through those holes from a higher surface. While I haven't tried it, the resolution *could* be adding surfaces atop the obstacles.

But it's possible that simply having a surface above another presents the nav package with a new challenge that needs to be addressed in a special way, but I would need time to look into that.

Is it possible you can share a repository with me reproducing this problem? I'd like to re-run the exact demo in the screenshot and investigate.

**Comment by kobechenyang** [comment] 2020-06-22 18:28
Hi Reese 
Sorry for not be very specific for the problem. I forked your repo and modified the navperformance demo. I put into this branch https://github.com/kobechenyang/ReeseUnityDemos/tree/dev
you can see my commits here https://github.com/kobechenyang/ReeseUnityDemos/commit/3ea4fc65798c20303aaa1080c7ceb4ce380010dc
I simply placed a 20x20 plane on top of a 100x100 plane. If I understand correctly how nav mesh works. When I set the NavMeshSurface Collect Objects to Children. It should stay within the current mesh? Right now they seems to be fall off the edge. 
Thanks !

**Comment by reeseschultz** [comment] 2020-06-22 20:15
Thanks @kobechenyang, I'll take a look at your scene soon.

**Comment by reeseschultz** [comment] 2020-06-23 14:22
**If you *don't* care about jumping**, note you were passing `20` as the `scale` to `NavUtil.GetRandomPointInBounds`. The surface is `20x20`, so by using `20` as the scale, the agents were too close to the edge. You could alternatively use, say, `19.5f`:

```c#
commandBuffer.AddComponent(entityInQueryIndex, entity, new NavNeedsDestination{
    Destination = NavUtil.GetRandomPointInBounds(
        ref random,
        renderBoundsFromEntity[surface.Value].Value,
        19.5f
    )
});
```
**If you *do* care about jumping**, I'm not immediately sure why the agents won't jump to the surface below, but I do know that the `NavPerformanceDemo` is not the right demo to test what's going on. I'll create one in a new branch and let you know what I find out.

**Comment by kobechenyang** [comment] 2020-06-24 03:03
> **If you _don't_ care about jumping**, note you were passing `20` as the `scale` to `NavUtil.GetRandomPointInBounds`. The surface is `20x20`, so by using `20` as the scale, the agents were to close to the edge. You could alternatively use, say, `19.5f`:
> 
> ```cs
> commandBuffer.AddComponent(entityInQueryIndex, entity, new NavNeedsDestination{
>     Destination = NavUtil.GetRandomPointInBounds(
>         ref random,
>         renderBoundsFromEntity[surface.Value].Value,
>         19.5f
>     )
> });
> ```

Ah. This did solve my problem. Thank you !

> 
> **If you _do_ care about jumping**, I'm not immediately sure why the agents won't jump to the surface below, but I do know that the `NavPerformanceDemo` is not the right demo to test what's going on. I'll create one in a new branch and let you know what I find out.

I did try set the jump surface dynamic buffer but it didn't work too.

**Comment by reeseschultz** [comment] 2021-01-24 15:07
I think the workaround mentioned resolved the issue. I can revisit it if needed later. Closing for now.

**Closed as completed by reeseschultz** 2021-01-24 15:07 UTC
Labels: triage
