### ISSUE TITLE
UnityEngine.Experimental.AI throws errors due to overlapping or touching surfaces

### ISSUE THREAD

**Issue by zlxt2714** [reeseschultz/ReeseUnityDemos#82] opened 2021-09-02 10:32 UTC
**Bug description:**

1. When the number of walking planes exceeds 2, or the number of planes exceeds 2, an AABB error will be reported when the agent reaches the end point（NavDestination  point）

you can copy your Surface and move it to  the  right  ,and  remove the wall     ,bake a new suface data  and test it .

**Bug reproduction:**

 
 
![82](https://user-images.githubusercontent.com/58289522/131828752-f71899b8-5d55-4c0b-b5e7-5c12e9f5c044.png)

![83](https://user-images.githubusercontent.com/58289522/131828881-0c05d64f-0c0d-4df3-aea6-b5bde9195846.png)
2. When I don't want to using the flocking effect, there is no mutual avoidance between agents

 

https://user-images.githubusercontent.com/58289522/131828910-625a2c8d-9242-4156-a292-f2fea7973e2a.mp4

I need your help

**Comment by reeseschultz** [comment] 2021-09-02 12:48
Okay, so there are two issues here, if I understand correctly.

1. One is that overlapping surfaces present AABB errors, presumably in one of the destination systems.
2. The other issue is that non-flocking agents do not avoid each other.

As to the first issue, one easy solution is to use a single mesh. You can either write or find a script to merge the meshes and bake them, or, preferably, just create a single mesh in Blender, or whatever your preferred 3D editor is. Would that resolve your issue?

As to the second issue, avoidance depends on flocking. The only way the agents can avoid each other is by flocking. No other avoidance strategies come with this code.

---

If you can't get what you need from my navigation package, you may want to look into [Godot 4's navigation server](https://godotengine.org/article/navigation-server-godot-4-0).

**Comment by zlxt2714** [comment] 2021-09-02 13:34
You understand very well. Thank you for your reply. My scene is very complex and there are a lot of models. Using a single mesh is not realistic. Where can I find a script to merge these meshes. can you give me a URL?

**Comment by reeseschultz** [comment] 2021-09-02 14:11
You're telling me that using a single mesh isn't realistic? Are you generating planes at runtime? If not, using a single mesh is entirely realistic.

I'm unaware of a one-size-fits-all scripts for runtime meshing. You can find examples with a search engine, some paid, some free.

**Comment by reeseschultz** [comment] 2021-09-02 14:35
Also, FYI, I can reproduce this issue, but I'm unsure when it will be resolved. This may be a bug in `UnityEngine.Experimental.AI`, not my code, which is why I'm suggesting workarounds. I'll need to take time out of my work to look at this.

**Comment by reeseschultz** [comment] 2021-09-02 15:51
Unfortunately, I'm 99% this is a Unity bug, and I can't do anything about it other than switch to a different DOTS-compatible navmesh API. Since none exist, we'll have to wait for Unity to update or replace `UnityEngine.Experimental.AI`.

Their [non-commital roadmap](https://unity.com/roadmap/unity-platform/navigation-game-ai) includes this relevant item:

> **Progressive Rearchitecture: Queryable navigation model**
> An enhanced set of API methods for querying the navigation data in greater detail than before, compatible with Unity’s Job System. The results include connectivity and geometry information about all the nodes in the navigation graph, and any other details necessary for implementing a pathfinding algorithm.

Looks like they intend on making my life much easier. In following this roadmap, one of the first things they did was start publishing https://github.com/Unity-Technologies/NavMeshComponents as a package, meaning I need to stop embedding its code directly in this project...

---

Anyway, I don't believe I can do anything about your issue @zlxt2714. You're welcome to reach out to Unity. Whether you do or 
not, the workaround is clear: you need a single mesh for navigation.

You may want to look into [Mesh.CombineMeshes](https://docs.unity3d.com/ScriptReference/Mesh.CombineMeshes.html). That's probably the easiest way to combine surfaces at runtime, although it won't cull duplicate polygons in the case of overlapping surfaces.

I'm closing this for now, unless someone has a solution that involves a simple code change to the nav package.

**Closed as completed by reeseschultz** 2021-09-02 15:51 UTC
Labels: bug-in-dependency

**Comment by zlxt2714** [comment] 2021-10-20 10:21
When I was using your Reese.Nav, I encountered a problem. When the target point （NavDestination （WorldPoint））is far away, the agent does not move to the target point. How can I modify the settings and  where can find the settings file  ? Thank you for your answer





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Reese ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reeseschultz/ReeseUnityDemos] [BUG]the number of planes exceeds 2, an AABB error will be reported when the agent reaches the end point（NavDestination  point） (#82)





 
Closed #82.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
