### ISSUE TITLE
Release more packages on OpenUPM

### ISSUE THREAD

**Issue by ptbarnaby** [reeseschultz/ReeseUnityDemos#77] opened 2021-08-04 15:17 UTC
Hi Reese,

Firstly thanks for the great package!

Is there any chance you could add Path to OpenUPM in the same way you've done for Nav? It would be great for us to use the OpenUPM package and easily stay up to date vs putting in a git branch and having to update it by editing the packages lock file

**Comment by reeseschultz** [comment] 2021-08-04 18:00
You're welcome!

I will add it to OpenUPM. There are other packages that need to be added as well. But! I desperately want to get away from package branching. I haven't confirmed this, but I think I can do something like:

`https://github.com/reeseschultz/ReeseUnityDemos.git?path=/Packages/com.some.package#SomeTag`

Effectively there we're just combining the tag and query syntax, and what I *want* to do, is to send that info to OpenUPM when I submit a package to it. I think, however, that will require changes to OpenUPM. It's assuming, for my monorepo at least, that I do all my package-specific tags in their own branches. I'll check with the maintainer, Favo, and see what he thinks. I really do not want to deal with these branches in my release automation anymore. In fact, I don't think anyone maintaining a monorepo particularly wants to do this. Previously we did it out of necessity, but a relatively modern Unity editor should be able to intrepret that string I mentioned above.

**Comment by reeseschultz** [comment] 2021-08-04 20:53
Please note that I created https://github.com/openupm/openupm/issues/2331 regarding the new releasing/packaging approach for monorepos.

**Comment by reeseschultz** [comment] 2022-01-10 11:48
Closing, since the `path` package was released months ago. I still need to get around to the tangential work mentioned in this issue.

**Closed as completed by reeseschultz** 2022-01-10 11:48 UTC
Labels: enhancement, discussion
