### ISSUE TITLE
Project packages not compiling without errors

### ISSUE THREAD

**Issue by airzocker** [reeseschultz/ReeseUnityDemos#91] opened 2021-11-14 12:21 UTC
Hi,
it currently seems like there are errors compiling just the used packages.
I'm using Unity 2020.3.18f1 (same as repo) also on Linux (Kubuntu 20.04).

This is just the Editor console output of the 95 occuring errors from the Collections package:

[console.log](https://github.com/reeseschultz/ReeseUnityDemos/files/7533673/console.log)

And here is my full editor log from just opening the project:

[full-editor.log](https://github.com/reeseschultz/ReeseUnityDemos/files/7533675/full-editor.log)

I hope we can get a working DOTS configuration again soon.

Regards,
Felix

**Comment by reeseschultz** [comment] 2021-11-14 19:11
Hello Felix! As we discussed on Discord, I said I'd look at this today.

Well, I did, and I'm a bit perplexed. Not sure if it's related, but, I had to *manually* [bump Burst to 1.4.11](https://github.com/reeseschultz/ReeseUnityDemos/commit/b1ee9196724ab6dd7b9403089ac4ef09da9c60f3) for the project to work (which you generally shouldn't do—the entities package is supposed to come with a compatible version of Burst behind the scenes). This is bizarre, because the project previously worked with the same editor and package versions a couple of months ago. All I can figure is that new, different artifacts are being pulled and cached from Unity in spite of the versions remaining the same. This is kind of scary. You'll notice that [1.4.11's changelog](https://docs.unity3d.com/Packages/com.unity.burst@1.4/changelog/CHANGELOG.html) reports "platform updates." Hmm....

My errors, however, were *not* the same as yours. Mine complained about `libdl.so`, which is extremely common when you don't have the right libraries on Linux.

Sooo... just to be sure, try manually updating Burst to the same version as me. Also, consider running this in your terminal (then restart the terminal/Unity Hub/Editor to be cautious):

```sh
sudo apt install gcc-multilib libncurses5 clang
```
I was under the impression that the Linux platform package was intended to do more heavy lifting in this regard, but perhaps that is not the case.

Furthermore, and more specifically, your errors seem to indicate either an issue with the package cache, or with the code generation associated with `Unity.Collections`. If none of the above helps, let me know, we can come up with other things to try. One avenue is deleting and regenerating the package cache in the `Library` directory. I'm not sure if that will work, though, because I know you had another project with the same issue. Please let me know what happens.

**Comment by airzocker** [comment] 2021-11-14 23:29
I just tested it on my other PC and it worked straight away without errors. It's pretty hard for me to test atm, maybe I will try these fixes tomorrow on the other laptop and report back the results.

**Comment by airzocker** [comment] 2021-11-15 13:58
Today I tested it on my other laptop again, where it didn't work. I installed all your suggested packages, and it definitely installed quite a bit, and also cloned the newest repo with the newer burst, but it still gave the exact same 95 errors as before (even rebooted after installing)...

**Comment by reeseschultz** [comment] 2021-11-15 16:27
One thing that comes to mind, given your log output, is that your Unity editor cannot read and/or write to the directory where the generated code should be in the package cache. One thing you could try is to recursively update the permissions in `Library/PackageCache`. Give that a shot. I feel like this is a permissions thing.

And, this is definitely an issue with your local environment, one that I have not been able to reproduce myself, nor locate elsewhere.

With that in mind, I'm going to close this issue for now since it doesn't appear to be an issue with the repo itself—but please continue updating myself and others in the Discord server. That's where we can continue to chat, and offer any advice we can come up with. That said, if updating permissions doesn't work, then I'm at a loss. If we can't figure out specifically what's causing the problem, then, as much as I hate to advise this, you may want to just reinstall your OS.

**Closed as completed by reeseschultz** 2021-11-15 16:27 UTC
Labels: triage
